
import { GoogleGenAI, Chat, Modality } from "@google/genai";

const getGenAI = () => {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable is not set.");
    }
    return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

export const translateHieroglyphs = async (base64Image: string, language: 'en' | 'ar'): Promise<string> => {
    const ai = getGenAI();
    const targetLanguage = language === 'en' ? 'English' : 'Arabic';

    const imagePart = {
        inlineData: {
            mimeType: 'image/jpeg',
            data: base64Image,
        },
    };

    const textPart = {
        text: `Analyze this image containing ancient Egyptian hieroglyphs. First, identify the hieroglyphs. Second, provide a translation of the text into modern ${targetLanguage}. Structure the response clearly. If no hieroglyphs are found, state that.`,
    };

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: { parts: [imagePart, textPart] },
    });

    return response.text;
};

export const analyzeArtifact = async (base64Image: string, language: 'en' | 'ar'): Promise<string> => {
    const ai = getGenAI();
    const targetLanguage = language === 'en' ? 'English' : 'Arabic';
    
    const imagePart = {
        inlineData: {
            mimeType: 'image/jpeg',
            data: base64Image,
        },
    };

    const textPart = {
        text: `Analyze this image of an ancient Egyptian artifact. Provide a detailed explanation in ${targetLanguage} covering:
        1. Identification of the artifact.
        2. Its historical period and significance.
        3. The symbolism of its features.
        4. Its purpose or use.
        Present this as a well-structured educational summary.`,
    };

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: { parts: [imagePart, textPart] },
    });

    return response.text;
};


export const renderRealisticImage = async (base64Image: string): Promise<string> => {
    const ai = getGenAI();
    
    const imagePart = {
        inlineData: {
            mimeType: 'image/jpeg',
            data: base64Image,
        },
    };

    const textPart = {
        text: `Based on this image of an ancient Egyptian artifact, generate a photorealistic, full-color rendering of what it would look like if it were brand new in 2025. Retain the original form and details, but use realistic materials (like polished gold, painted stone, etc.) and cinematic lighting. The output must be just the image.`,
    };
    
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: { parts: [imagePart, textPart] },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }
    
    throw new Error("No image was generated by the API.");
};


let chatInstance: Chat | null = null;

export const getChat = (): Chat => {
    if (!chatInstance) {
        const ai = getGenAI();
        chatInstance = ai.chats.create({
            model: 'gemini-2.5-flash',
            config: {
                systemInstruction: 'You are a friendly and knowledgeable expert on ancient Egypt, working as a virtual guide for the Grand Egyptian Museum. Answer questions with enthusiasm and historical accuracy. Keep responses concise and engaging. Respond in the language of the user\'s query (English or Arabic).',
            },
        });
    }
    return chatInstance;
};
